### PR TITLE
add covid19 screener completion event to dashboard

### PR DESCRIPTION
**Pull request by mchelen-gov**

### CODE REVIEW

**Comment by shefalinayak** [comment]
@mchelen Are you expecting the number of transactions to currently be zero? These are today's numbers for this branch:

Screen Shot 2020-11-11 at 10 19 43

**Review by shefalinayak — APPROVED** [review]

**Comment by mchelen-gov** [comment]
@shefalinayak Ah nope, it should be something like 1.3m. Based on our GA dashboard: https://analytics.google.com/analytics/web/?authuser=2#/dashboard/qHm9KfILQnmYWnUVDycH0w/a50123418w177519031p184624291/_u.dateOption=last30days/

image

**Comment by shefalinayak** [comment]
@mchelen-gov It looks like your GA dashboard is using covid-screening-tool-result as the Event Label filter, and you have it in this PR as an Event Action filter. And with an initial poke at GA, I think the Event Category is Interactions, not Transactions.

The performance dashboard currently only supports three filter types for GA: page path, event category, and event action. I'm not sure you'll be able to get the metric you're looking for using those filters. It shouldn't be hard to add a fourth filter, but it does require a code change.

I'm going to close this PR to avoid confusion, since I had approved it but it won't work as-is.

**Comment by mchelen-gov** [comment]
@kennedycollins thanks for the info! tried updating that config here: https://github.com/department-of-veterans-affairs/vets.gov-status/commit/da4ea3ff8f81afb30ab21078211bf95e29d7498a

**Review by shefalinayak — APPROVED** [review]
Looks good!

Screen Shot 2020-11-12 at 09 47 02

**Pull request merged**
