### PR TITLE
Add Covid vaccination sign-ups to health tools

### PR DESCRIPTION
**Pull request by stephenBarrs**
This PR adds a new `tool` to the Health Care `Service` for COVID-19 Vaccine interest form submissions.  This data is retrieved from GA with this configuration:

```
- title: "COVID-19 Vaccine interest form submissions"
        page_path_filter: "/health-care/covid-19-vaccine/stay-informed/form/"
        event_category_filter: "Transactions"
        event_action_filter: "Forms"
```

[Here is the link to the GA page](https://analytics.google.com/analytics/web/#/report/content-event-pages/a50123418w177519031p184624291/_u.date00=20210201&_u.date01=20210204&_r.drilldown=analytics.pagePath:~2Fhealth-care~2Fcovid-19-vaccine~2Fstay-informed~2Fform~2F,analytics.eventCategory:Transactions,analytics.eventAction:Forms&explorer-table.plotKeys=%5B%5D/) that is being tracked.  

- This part was a bit confusing to me as I wanted to track based on `ga:eventLabel==covid-vaccination--submission-successful` but did not see a way to fetch the GA results by eventLabel.  It seems that tracking the page as configured above returns accurate results but would appreciate a review of that implementation.  

Also, it appears the auto formatter in my VS Code changed all the `'` into `"`.  If this is an issue LMK and I can fix.  The fetch-data-local script works locally and pulls down all data.  

All unit-tests are passing
ui-tests are not executing due to an error locally 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/19308

### CODE REVIEW

**Comment by karlbrown-va** [comment]
would you mind fixing the quotes that were added? It will make the diff easier to read.

**Comment by stephenBarrs** [comment]
> would you mind fixing the quotes that were added? It will make the diff easier to read.

@karlbrown-va quotes have been reverted.  Thanks!

**Comment by kennedycollins** [comment]
Reviewed the query — it looks good to me, although if you start to record events with a different label from the same form (such as failed submissions), they would also show up. No way around that right now, but you're not the first team to want an event label filter. Perhaps that would be a good addition at some point soon.

**Comment by shefalinayak** [comment]
Looks good to me

**Review by saman-moshafi-va — APPROVED** [review]
Looks good to me

**Pull request merged**
