### PR TITLE
Don't tie Jenkins to any particular agent

### PR DESCRIPTION
**Pull request by jkassemi**
ref https://github.com/department-of-veterans-affairs/devops/pull/1887

### CODE REVIEW

**Comment by robertfairhead** [comment]
@jkassemi I believe this was tied to rails-testing because those were configured some access this needed (S3?). Ken set it up a long time ago, but i remember something like that.

```
[s_jk-jenkins-agent-agnostic-TLJRRQQOWPLNSCI4F3P4DWHVKVOKS7O3UOWYNV3BBF77U74QL2HA] Running shell script
+ bash --login -c bundle
bash: bundle: command not found
script returned exit code 127
```

The failure above on the updated Jenkinsfile.

I'll take a look on Monday and see about getting this PR passing and merge it in.

**Comment by jkassemi** [comment]
Thanks @robertfairhead - I'm working on getting all the Jenkins slave nodes set up identically so we can better handle distributing the load; I'll make sure the dependencies get into place for this one, but will ping you if I run into further issues.

**Comment by robertfairhead** [comment]
@jkassemi Giving this some thought, the issue is that jekyll needs rails stuff (bundle, etc.) available which were on the `rails-testing` nodes and not the one that failed above.

It should be fairly trivial to convert the jenkinsfile to use jekyll via docker instead of installing the ruby stack on all the jenkins nodes. i can do that on monday and update the PR unless you're 👎  on that plan.

**Comment by jkassemi** [comment]
I'm 👍👍 on that plan - moving toward dockerizing all project builds is on our list. Thanks!

**Comment by jkassemi** [comment]
Thanks @robertfairhead! We're setting up with a new name now; just added the label. Will keep you posted when we get the new swarm nodes online.

**Comment by robertfairhead** [comment]
@jkassemi Sounds good. I should have this working later today or early tomorrow. The default jekyll image builds off Alpine, which seems to be causing some permissions issue in the interaction with Jenkins (as best I can tell). I'm messing with it a bit between other tasks, but should have an hour or two to focus on it at some point.

**Pull request merged**
